---
- name: Install prerequisites for Caddy
  apt:
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
    state: present

- name: Add Caddy's official GPG key
  shell: "curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg"
  args:
    creates: /usr/share/keyrings/caddy-stable-archive-keyring.gpg

- name: Add the Caddy repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
    state: present
    filename: caddy-stable

- name: Update apt and install Caddy
  apt:
    name: caddy
    update_cache: yes
    state: present

- name: Create Caddyfile from template
  template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
  notify: Reload Caddy

- name: Ensure Caddy service is started and enabled
  systemd:
    name: caddy
    state: started
    enabled: yes
